---
- name: Update and Deploy to k3s Cluster
  hosts: localhost
  become: true
  vars:
    backend_image_tag: "{{ backend_image_tag }}"
    frontend_image_tag: "{{ frontend_image_tag }}"
  
  tasks:
    - name: Debug k3s connectivity
      command: kubectl get nodes --kubeconfig=/etc/rancher/k3s/k3s.yaml
      register: kubectl_output
    - debug: msg="{{ kubectl_output.stdout_lines }}"

    
    - name: Set Backend Image
      become: true
      kubernetes.core.k8s:
        kubeconfig: "/etc/rancher/k3s/k3s.yaml"
        state: present
        definition:
          kind: Deployment
          apiVersion: apps/v1
          metadata:
            name: password-generator-backend
            namespace: default
          spec:
            template:
              spec:
                containers:
                - name: backend
                  image: "kimo23/password-generator-backend:{{ backend_image_tag }}"
                  
    - name: Set Frontend Image
      kubernetes.core.k8s:
        kubeconfig: "/etc/rancher/k3s/k3s.yaml"
        state: present
        definition:
          kind: Deployment
          apiVersion: apps/v1
          metadata:
            name: password-generator-frontend
            namespace: default
          spec:
            template:
              spec:
                containers:
                - name: frontend
                  image: "kimo23/password-generator-frontend:{{ frontend_image_tag }}"
