---
- name: Deploy Application to k3s
  hosts: localhost
  become: true
  tasks:
    - name: Deploy backend
      community.kubernetes.k8s:
        kubeconfig: "/etc/rancher/k3s/k3s.yaml"
        state: present
        force: yes
        definition: "{{ lookup('file', 'backend-deployment.yaml') }}"
        
    - name: Deploy frontend
      community.kubernetes.k8s:
        kubeconfig: "/etc/rancher/k3s/k3s.yaml"
        state: present
        force: yes
        definition: "{{ lookup('file', 'frontend-deployment.yaml') }}"
