global:
  scrape_interval: 15s  # How often Prometheus scrapes metrics
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'k3s-application'
    static_configs:
      - targets: ['localhost:32435']  # The application's address
